FROM node:14 as builder
WORKDIR /usr/src/app

RUN curl -sf https://gobinaries.com/tj/node-prune | sh

COPY package.json yarn.lock ./
RUN yarn

COPY . .
ENV NODE_ENV=production
RUN yarn build

ENV NODE_ENV=production
RUN yarn

RUN node-prune

FROM node:14-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

CMD ["node", "dist/main"]
